apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    tier: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        tier: frontend
    spec:
      containers:
        - name: frontend-container
          image: "{{ .Values.frontend.image }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
          env:
            - name: BACKEND_URL
              value: "http://{{ .Values.backend.service.name }}.{{ .Values.backend.namespace }}.svc.cluster.local:{{ .Values.backend.service.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app }}
    tier: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ .Values.app }}
    tier: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
