apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.app }}
    tier: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        tier: frontend
    spec:
      containers:
        - name: frontend-container
          image: "{ .Values.frontend.image }"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.service.name }}
  labels:
    app: {{ .Values.app }}
    tier: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ .Values.app }}
    tier: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
