app: todolist-app
namespace: frontend

frontend:
  name: frontend
  replicas: 1
  image: joselin721/frontend
  containerPort: 3000
  service:
    name: frontend-svc
    type: NodePort
    port: 3000
    nodePort: 30000

backend:
  namespace: backend
  service:
    name: backend-svc
    port: 5000
